- _mk-at-zhenghua/About Us.md
- _our-info-hub/Information for Parents/Open House 2023.md
1. Correct MK teachers name
2. Input P1 Open House schedule
> Update MK teacher and 2023 Open House

- _about-us/Our People/Primary 4.md
- _our-info-hub/Information for Parents/Primary 1 Matters.md
> Update our people page

- _about-us/Our People/Primary 1.md
- _our-info-hub/School Services/School Bus Service.md
- _our-info-hub/collection.yml
1. Update P1 teachers email address
2. Add School Bus Operator
> Update email address and Bus Operator

- _our-info-hub/Useful Links/2023 SDL Day.md
1. Add linkable SDL image to SDL page
> Add SDL image

- _our-info-hub/Information for Parents/Information for P6 Parents.md
- _zps/Announcements.md
1. Update WE stories 2023 publication -> /our-info-hub/information-for-parents/info-for-p6-parents/
> Update WE Stories 2023 Publication

- _about-us/Our People/Key Personnel.md
> Update Jolene to SH

- _about-us/Our People/Admin & SAT.md
> Update "People"-> Admin/SAT

- _our-info-hub/Information for Parents/Primary 1 Matters.md
Added P1 Orientation (For 2024) to Our Info Hub
> Add P1 Orientation (For 2024)

- _our-info-hub/Information for Parents/Primary 1 Matters.md
> Update P1 Orientation

- _our-info-hub/Useful Links/Home Based Learning.md
remove HBL links in our info hub>useful links>HBL
> remove HBL links

- _our-info-hub/Useful Links/Home Based Learning.md
> Add HBL for Week 3

- _our-info-hub/Useful Links/Home Based Learning.md
addded HBL links for 28-29 Sep 2023 again
> Add HBL for 28-29 Sep

- _our-info-hub/Useful Links/Home Based Learning.md
> Updated HBL page

- _our-info-hub/Useful Links/Home Based Learning.md
Update HBL link for Term 4 Week 4 2023
> Update HBL for term 4 week4 2023

- _our-info-hub/Useful Links/Home Based Learning.md
> add back HBL for week 3

- _our-info-hub/Useful Links/Insurence Claim Form.md
- _our-info-hub/collection.yml
Add Insurance Claim Form to useful link
> Add Insurance Claim Form

- _our-info-hub/Useful Links/2023 SDL Day.md
> Update SDL page

- _our-info-hub/Useful Links/Home Based Learning.md
Update HBL for P1,2 &6 for week 6
> Updated HBL for Week 6

- _zhps-experience/Mathematics.md
Fixed name error ZHPS Experience>Math
> Fixed name error ZHPS Experience>Math

- _our-info-hub/Staff Achievements/2023.md
> Edit Staff Achievements

- _our-info-hub/Staff Achievements/2023.md
> Update Staff Achievement

- _about-us/Our People/Allied Educators.md
- _about-us/Our People/MK@Zhenghua.md
- _about-us/Our People/Primary 1.md
- _about-us/Our People/Primary 2.md
- _about-us/Our People/Primary 3.md
- _about-us/Our People/Primary 4.md
- _about-us/Our People/Primary 5.md
- _about-us/Our People/Primary 6.md
> changes to form teacher

- _about-us/Our People/Allied Educators.md
Added and deleted Teachers for 2024
> Added and deleted Teachers for 2024

- _about-us/Our People/Key Personnel.md
> Update KP personnal

- _about-us/Our People/Primary 6.md
- _our-info-hub/School Services/Facilities.md
Update Teacher's name and Canteen price list
> Update Teacher's name and Canteen price list

- _about-us/Our People/Key Personnel.md
- _about-us/Our People/Primary 1.md
- _about-us/Our People/Primary 2.md
- _about-us/Our People/Primary 5.md
> Moved 5RE to bottom row

- _about-us/Our People/Primary 1.md
- _about-us/Our People/Primary 4.md
- _media-gallery/2024.md
- _media-gallery/collection.yml
- _mk-at-zhenghua/Gallery/2024.md
- _mk-at-zhenghua/collection.yml
- _our-info-hub/Information for Parents/Parents' Briefing.md
- _our-info-hub/Information for Parents/Parents' Briefing1.md
- _our-info-hub/Useful Links/2023 SDL Day.md
- _our-info-hub/Useful Links/2024 SDL Day.md
- _our-info-hub/Useful Links/Home Based Learning.md
- _our-info-hub/Useful Links/Student Learning Space.md
- _our-info-hub/collection.yml
> Remove 2023 Parents' Briefing

- _our-info-hub/Our Partners/Parents' Support Group.md
Update Info Hub Page - Parents Support Group
> Update Info Hub Page - Parents Support Group

- _about-us/Our School Identity/School Song.md
> Update School Song

- _about-us/Our People/Primary 1.md
> Update 1HY teacher 

- _about-us/Our People/Admin & SAT.md
- _our-info-hub/Useful Links/2024 SDL Day.md
> Update Admin & SAT

- _our-info-hub/Useful Links/2024 SDL Day.md
- _our-info-hub/Useful Links/SDL Day.md
- _our-info-hub/collection.yml
> Edit SDL Day

- _our-info-hub/Useful Links/SDL Day.md
> Updated SDL Day Page

- _for-staff-only/Estate Management and Operations.md
- _our-info-hub/Contact Us.md
- _our-info-hub/Our Partners/Alumni.md
- _our-info-hub/Our Partners/Community Partners.md
- _our-info-hub/Our Partners/Parents' Support Group.md
- _our-info-hub/Our Partners/School Advisory Committee.md
- _our-info-hub/Privacy Policy.md
- _our-info-hub/School Services/Facilities.md
- _our-info-hub/School Services/School Bus Service.md
- _our-info-hub/School Services/School Canteen.md
> Updated different pages

- _for-staff-only/Procurement for Goods and Services.md
> Updated "For Staff Only" page

- _our-info-hub/Information for Parents/Primary 1 Matters.md
- _our-info-hub/School Services/Student Care Centre.md
> Updated P1 Matters

- _our-info-hub/School Services/Student Care Centre.md
update school services -> student care centre
> update school services -> student care centre

- _our-info-hub/Information for Parents/School Term Calendar.md
> update school term calendar

- _performing-and-visual-arts/Brass Band.md
- _performing-and-visual-arts/Chinese Dance.md
- _performing-and-visual-arts/Choir.md
- _performing-and-visual-arts/Indian Dance.md
- _performing-and-visual-arts/Malay Dance.md
Update performing-and-visual-arts page
> Update performing-and-visual-arts page

- _about-us/Our People/Admin & SAT.md
> Update People Page

- _about-us/Our People/Admin & SAT.md
> Up SAT People Page

- _mk-at-zhenghua/Gallery/2024.md
> Update 2024 MK Gallery

- pages/privacy.md
- pages/terms-of-use.md
Update PRIVACY STATEMENT and Terms of Use
> Update PRIVACY STATEMENT and Terms of Use

- _about-us/Our People/Primary 2.md
edited simwenyan's name which was wrongly displayed
> our people 

- _our-info-hub/Information for Parents/Open House.md
principal briefing slide uploaded
> open house page

- _about-us/Our People/Admin & SAT.md
> updated AM to people page

- _our-info-hub/Our Partners/School Advisory Committee.md
> Update SAC names

- _our-info-hub/Useful Links/Home Based Learning.md
> Updated HBL

- _our-info-hub/Useful Links/Home Based Learning.md
> Added HBL link

- _our-info-hub/Information for Parents/Primary 1 Matters.md
> Update P1 Orientation 2025

- _for-staff-only/Procurement for Goods and Services.md
- _our-info-hub/Useful Links/Home Based Learning.md
> Update HBL and added AOR form

- _our-info-hub/Useful Links/Home Based Learning.md
> Update HBL for 13th Sep 2024

- _our-info-hub/Useful Links/Home Based Learning.md
> Update P4 HBL

- _zhps-experience/Physical & Outdoor Education.md
> Update Zhenghua Experience

- _our-info-hub/School Services/School Bus.md
> Update School Bus info

- _our-info-hub/Useful Links/Home Based Learning.md
- _zps/Announcements.md
Update School Bus services and HBL links for P1, P2 and P6
> Update School Bus services and HBL links for P1, P2 and P6

- _our-info-hub/Useful Links/Leave of Absence.md
> Update LOA form

- _mk-at-zhenghua/Gallery/2024.md
> Update MK Term 3 Gallery

- _about-us/Our People/Key Personnel.md
- _our-info-hub/Information for Parents/Parents' Briefing.md
> update P1-P6 Briefing page

- _about-us/Our People/Key Personnel.md
- _about-us/Our People/Primary 1.md
- _about-us/Our People/Primary 2.md
- _our-info-hub/Useful Links/Library Resources.md
Update P1 teachers and Library Resources
> Update P1 teachers and Library Resources

- _about-us/Our People/MK@Zhenghua.md
- _for-staff-only/Procurement for Goods and Services.md
- _mk-at-zhenghua/About Us.md
Remove Bus Booking and AOR forms
> Remove Bus Booking and AOR forms

- _our-info-hub/Useful Links/MIMS and SLS Self Help Guide.md
Added SLS and MIMS login and reset password video
> Added SLS and MIMS login and reset password video

- _about-us/Our People/Allied Educators.md
- _our-info-hub/School Services/Dental Clinic.md
- _our-info-hub/School Services/Student Care Centre.md
- _our-info-hub/collection.yml
> update various pages

- _about-us/Our People/Primary 1.md
update teacher's email address
> update teacher's email address

- _about-us/Our People/Key Personnel.md
> Update Staff Titles

- _our-info-hub/Information for Parents/Parents' Briefing.md
Update P2 - P6 student briefing
> Update student briefing

- _our-info-hub/Information for Parents/Primary 1 Matters.md
- _our-info-hub/Useful Links/Home Based Learning.md
> updated pages

- _our-info-hub/Useful Links/Library Resources.md
Update OUR INFOR HUB / USEFUL LINKS / LIBRARY RESOURCES
> Update OUR INFOR HUB / USEFUL LINKS / LIBRARY RESOURCES

- _zps/Announcements.md
> Update broken links

- _mk-at-zhenghua/Gallery/2025.md
- _mk-at-zhenghua/Gallery/Exam2025ple Title.md
- _mk-at-zhenghua/collection.yml
> Updated MK Gallery 2025

- _contact-us/MOE Kindergarten@Zhenghua.md
> Update MK phone number

- _contact-us/MOE Kindergarten@Zhenghua.md
made changes to MK phone number
> made changes to MK phone number

- _our-info-hub/Student Achievements/2024.md
> Update Student Achievements

- _mk-at-zhenghua/Gallery/2025.md
> Added MK Term 2 Gallery

- _our-info-hub/Useful Links/Home Based Learning.md
> remove HBL

- _our-info-hub/Useful Links/Financial Assistance.md
Update Financial Assistance page
> Update Financial Assistance page

- _our-info-hub/Useful Links/Home Based Learning.md
Added P4 HBL for 29th Sep 2025
> Added P4 HBL for 29th Sep 2025
